ROOT=..$(%SEP)..
PROJ=test$(%SEP)16bit
PATH=..$(%SEP)..$(%SEP)$(PROJ)

DESC="Test cases"

!include ..$(%SEP)..$(%SEP)makefile.mk

COPT=-bt=os2 -3 -s -sg -db -d2 -hw -ml -od -zq -q -fp3 -fpi87 -i=. -i=.. -i=..$(%SEP)..$(%SEP)include -i=$(%WATCOM)$(%SEP)h -i=$(%WATCOM)$(%SEP)h$(%SEP)os21x

TARGETS=$(BINROOT)$(%SEP)test$(%SEP)memtest.exe &
        $(BINROOT)$(%SEP)test$(%SEP)qfs.exe &
        $(BINROOT)$(%SEP)test$(%SEP)test.exe &
!ifeq %OS os2
        $(BINROOT)$(%SEP)test$(%SEP)memtest.sym &
        $(BINROOT)$(%SEP)test$(%SEP)qfs.sym &
        $(BINROOT)$(%SEP)test$(%SEP)test.sym
!endif

OBJS1=$(PROJ_BLD)$(%SEP)memtest.obj
OBJS2=$(PROJ_BLD)$(%SEP)qfs.obj
OBJS3=$(PROJ_BLD)$(%SEP)test.obj

SYS=os2

$(BINROOT)$(%SEP)test$(%SEP)memtest.exe:

$(BINROOT)$(%SEP)test$(%SEP)qfs.exe:

$(BINROOT)$(%SEP)test$(%SEP)test.exe:

$(BINROOT)$(%SEP)test$(%SEP)memtest.sym:

$(BINROOT)$(%SEP)test$(%SEP)qfs.sym:

$(BINROOT)$(%SEP)test$(%SEP)test.sym:

$(PROJ_BLD)$(%SEP)memtest.lnk: $(PROJ_BLD)$(%SEP)memtest.ols

$(PROJ_BLD)$(%SEP)qfs.lnk: $(PROJ_BLD)$(%SEP)qfs.ols

$(PROJ_BLD)$(%SEP)test.lnk: $(PROJ_BLD)$(%SEP)test.ols

$(PROJ_BLD)$(%SEP)memtest.ols: $(OBJS1) makefile.wcc ..$(%SEP)..$(%SEP)makefile.mk
 @%create $^@
 @for %e in ($(OBJS1)) do @%append $^@ FILE %e
 
$(PROJ_BLD)$(%SEP)qfs.ols: $(OBJS2) makefile.wcc ..$(%SEP)..$(%SEP)makefile.mk
 @%create $^@
 @for %e in ($(OBJS2)) do @%append $^@ FILE %e

$(PROJ_BLD)$(%SEP)test.ols: $(OBJS3) makefile.wcc ..$(%SEP)..$(%SEP)makefile.mk
 @%create $^@
 @for %e in ($(OBJS3)) do @%append $^@ FILE %e

.ols.lnk:
 @%create $@
 @%append $@ SYSTEM $(SYS)
 @%append $@ NAME $(BINROOT)$(%SEP)test$(%SEP)$^&.exe
 @%append $@ OPTION DESCRIPTION '$(FILEVER)  $(DESC)'
 @%append $@ OPTION ST=32000
 @%append $@ OPTION HEAP=32000
 @%append $@ OPTION QUIET
 @%append $@ DEBUG ALL
 @%append $@ OPTION MAP=$[*.wmp
 @%append $@ LIBPATH $(%WATCOM)$(%SEP)lib286;$(%WATCOM)$(%SEP)lib286$(%SEP)os2;$(LIBROOT)
 @%append $@ LIB os2,clibs
 @%append $@ @$[@
