!define _32BITS
ROOT=..
PROJ=test
PATH=..\..\$(PROJ)
DIRS=16bit

DESC="Test cases"

!include ..\makefile.mk

COPT=-3s -s -sg -db -d2 -hw -mf -od -zq -q -fp3 -fpi87 -i=. -i=.. -i=..\include -i=$(%WATCOM)\h -i=$(%WATCOM)\h\os2

TARGETS=$(BINROOT)\test\dumpmsg.exe $(BINROOT)\test\dumpmsg.sym &
        $(BINROOT)\test\info.exe $(BINROOT)\test\info.sym &
        $(BINROOT)\test\jpgdup.exe $(BINROOT)\test\jpgdup.sym &
        $(BINROOT)\test\mfile.exe $(BINROOT)\test\mfile.sym &
        $(BINROOT)\test\mtest.exe $(BINROOT)\test\mtest.sym &
        $(BINROOT)\test\nls.exe $(BINROOT)\test\nls.sym &
        $(BINROOT)\test\qpath.exe $(BINROOT)\test\qpath.sym &
        $(BINROOT)\test\ttt.exe $(BINROOT)\test\ttt.sym

OBJS1=$(PROJ_BLD)\dumpmsg.obj
OBJS2=$(PROJ_BLD)\info.obj
OBJS3=$(PROJ_BLD)\jpgdup.obj
OBJS4=$(PROJ_BLD)\mfile.obj
OBJS5=$(PROJ_BLD)\mtest.obj
OBJS6=$(PROJ_BLD)\nls.obj
OBJS7=$(PROJ_BLD)\qpath.obj
OBJS8=$(PROJ_BLD)\ttt.obj

SYS=os2v2

$(BINROOT)\test\dumpmsg.exe:

$(BINROOT)\test\info.exe:

$(BINROOT)\test\jpgdup.exe:

$(BINROOT)\test\mfile.exe:

$(BINROOT)\test\mtest.exe:

$(BINROOT)\test\nls.exe:

$(BINROOT)\test\qpath.exe:

$(BINROOT)\test\ttt.exe:

$(BINROOT)\test\dumpmsg.sym:

$(BINROOT)\test\info.sym:

$(BINROOT)\test\jpgdup.sym:

$(BINROOT)\test\mfile.sym:

$(BINROOT)\test\mtest.sym:

$(BINROOT)\test\nls.sym:

$(BINROOT)\test\qpath.sym:

$(BINROOT)\test\ttt.sym:

$(PROJ_BLD)\dumpmsg.lnk: $(PROJ_BLD)\dumpmsg.ols

$(PROJ_BLD)\info.lnk: $(PROJ_BLD)\info.ols

$(PROJ_BLD)\jpgdup.lnk: $(PROJ_BLD)\jpgdup.ols

$(PROJ_BLD)\mfile.lnk: $(PROJ_BLD)\mfile.ols

$(PROJ_BLD)\mtest.lnk: $(PROJ_BLD)\mtest.ols

$(PROJ_BLD)\nls.lnk: $(PROJ_BLD)\nls.ols

$(PROJ_BLD)\qpath.lnk: $(PROJ_BLD)\qpath.ols

$(PROJ_BLD)\ttt.lnk: $(PROJ_BLD)\ttt.ols

$(PROJ_BLD)\dumpmsg.ols: $(OBJS1) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS1)) do @%append $^@ FILE %e

$(PROJ_BLD)\info.ols: $(OBJS2) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS2)) do @%append $^@ FILE %e

$(PROJ_BLD)\jpgdup.ols: $(OBJS3) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS3)) do @%append $^@ FILE %e

$(PROJ_BLD)\mfile.ols: $(OBJS4) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS4)) do @%append $^@ FILE %e

$(PROJ_BLD)\mtest.ols: $(OBJS5) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS5)) do @%append $^@ FILE %e

$(PROJ_BLD)\nls.ols: $(OBJS6) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS6)) do @%append $^@ FILE %e

$(PROJ_BLD)\qpath.ols: $(OBJS7) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS7)) do @%append $^@ FILE %e

$(PROJ_BLD)\ttt.ols: $(OBJS8) makefile.wcc ..\makefile.mk
 @%create $^@
 @for %e in ($(OBJS8)) do @%append $^@ FILE %e

.ols.lnk:
 @%create $@
 @%append $@ SYSTEM $(SYS)
 @%append $@ NAME $(BINROOT)\test\$^&.exe
 @%append $@ OPTION DESCRIPTION '$(FILEVER)  $(DESC)'
 @%append $@ OPTION ST=64000
 @%append $@ OPTION HEAP=64000
 @%append $@ OPTION QUIET
 @%append $@ DEBUG ALL
 @%append $@ OPTION MAP=$[*.wmp
 @%append $@ LIBPATH $(%WATCOM)\lib386;$(%WATCOM)\lib386\os2;$(LIBROOT)
 @%append $@ LIB os2386,clib3s
 @%append $@ @$[@
