ROOT=..$(%SEP)..
PROJ=ifsinf
PATH=..$(%SEP)..$(%SEP)$(PROJ)

!include ..$(%SEP)..$(%SEP)makefile.mk

TARGETS = $(BINROOT)$(%SEP)os2$(%SEP)book$(%SEP)ifs.inf
DIRS=

$(BINROOT)$(%SEP)os2$(%SEP)book$(%SEP)ifs.inf:
